### ISSUE TITLE
Allow saving POIs

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/whogo-maps#3]
Previous dicussion: https://github.com/otsaloma/poor-maps/issues/3

**Comment by rinigus** [comment]
After the work on styling the map interface, I was thinking about looking into this. Its a feature that I miss and would like to get it implemented.

Do you have any thoughts regarding this? I am considering using flat list of GeoJSON objects as a format with icon, name, and the place in POI hierarchy given in the properties of GeoJSON object. This would allow to use the same POIs to save anything that can be contained in GeoJSON - from points to routes and their collections, for example. 

Alternative would be to have SQLite and then populate map objects from there. This would simplify the search by the names and categories. It would probably scale better since the search is offloaded to the db code. Again, we could keep geo data in GeoJSON-compatible way, so its easy to populate the map from it too.

**Comment by rinigus** [comment]
Started reading POI implementation that is in the code already. Its lot that has been done and I better step down from it, for now at least, and not interfere here - it will require some time to catch up with the code. Sorry for the noise.
