### ISSUE TITLE
have an option not to use tolls on routing in osmscout

### ISSUE THREAD

**Issue by legacychimera247** [otsaloma/whogo-maps#54]
well the title pretty much explain everything, it would be nice to have a way to calculate routes with tolls or not...since opencage have it maybe even osmscout can have it...

**Comment by rinigus** [comment]
I can work on it, seems to be rather trivial to add the support for. However, I would prefer the work on navigation that I have been doing to be merged first. This is due to some changes introduced there to support concise displays of the maneuvers and getting additional data regarding them. So, please wait a bit, we'll be able to add costing options in future.
